#Configuration example
[tool.ruff]
lint.select = [
  "F",
  "E",
  "W",
  "C90",
  "N",
  "D",
  "A",
  "ANN",
  "S",
  "COM",
  "Q",
  "ARG",
  "PTH",
  "PD",
  "NPY",
]

lint.ignore = ["D100", "D203", "D211", "D213", "COM812"]
